### ISSUE TITLE
Error installing PyYAML during setup-python@v4 step

### ISSUE THREAD

**Issue by richm** [ansible-community/ansible-test-gh-action#64] opened 2023-07-18 17:51 UTC
https://github.com/linux-system-roles/kernel_settings/actions/runs/5590666395/jobs/10220681606
```python-traceback
+ python -m pip install 'PyYAML>5,<6' --disable-pip-version-check --user
Collecting PyYAML<6,>5
  Downloading PyYAML-5.4.1.tar.gz (175 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 175.1/175.1 kB 4.5 MB/s eta 0:00:00
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [68 lines of output]
      /tmp/pip-build-env-kdyhx5qx/overlay/lib/python3.11/site-packages/setuptools/config/setupcfg.py:293: _DeprecatedConfig: Deprecated config in `setup.cfg`
      !!
...
      Traceback (most recent call last):
        File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
...
        File "/tmp/pip-build-env-kdyhx5qx/overlay/lib/python3.11/site-packages/setuptools/_distutils/command/sdist.py", line 336, in _add_defaults_ext
          self.filelist.extend(build_ext.get_source_files())
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<string>", line 201, in get_source_files
        File "/tmp/pip-build-env-kdyhx5qx/overlay/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 107, in __getattr__
          raise AttributeError(attr)
      AttributeError: cython_sources
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
Error: Process completed with exit code 1.
```

**Comment by felixfontein** [comment] 2023-07-18 20:02
This is caused by PyYAML and should be fixed by the latest PyYAML 6.0.1 release from today. Unfortunately this action forcess PyYAML < 6 (https://github.com/ansible-community/ansible-test-gh-action/blob/main/action.yml#L226)...

**Comment by felixfontein** [comment] 2023-07-18 20:16
#65 fixes the problem.

**Closed** 2023-07-19 08:15 UTC
